[package]
name = "dashboard-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parquet = "51.0.0"
rocket = "0.5.0"
rocket_contrib = "0.4.11"
